import {
  ApplicationConfig,
  importProvidersFrom,
  provideZonelessChangeDetection,
} from "@angular/core";
import {
  ArrowUpRight,
  CalendarDays,
  Camera,
  ChartNoAxesCombined,
  Check,
  CheckCheck,
  ChevronDown,
  ChevronRight,
  Clock,
  Download,
  Droplets,
  Ellipsis,
  FlaskConical,
  Grape,
  LayoutDashboard,
  Leaf,
  LogOut,
  LucideAngularModule,
  MapPin,
  Menu,
  NotebookPen,
  Pencil,
  Plus,
  Scissors,
  Search,
  Settings,
  Sprout,
  Trash2,
  TriangleAlert,
  Wallet,
  X,
} from "lucide-angular";

export const appConfig: ApplicationConfig = {
  providers: [
    provideZonelessChangeDetection(),
    importProvidersFrom(
      LucideAngularModule.pick({
        LayoutDashboard,
        Sprout,
        NotebookPen,
        CalendarDays,
        ChartNoAxesCombined,
        Settings,
        Plus,
        Search,
        ChevronDown,
        ChevronRight,
        ArrowUpRight,
        Droplets,
        Scissors,
        FlaskConical,
        Grape,
        MapPin,
        Check,
        X,
        Download,
        Leaf,
        Menu,
        LogOut,
        Ellipsis,
        Camera,
        Trash2,
        Pencil,
        TriangleAlert,
        Wallet,
        Clock,
        CheckCheck,
      }),
    ),
  ],
};
